musicproject/mcproject/mcproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('musicapp.urls')),
]
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

musicproject/mcproject/musicapp/urls.py
from django.urls import path
from . import views
app_name='musicapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('music/<int:music_id>/',views.detail,name='detail'),
    path('add/',views.add_music,name='add_music'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

musicproject/mcproject/musicapp/models.py
from django.db import models

# Create your models here.

class music(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

musicproject/mcproject/musicapp/forms.py
from django import forms
from . models import music

class MusicForm(forms.ModelForm):
    class Meta:
        model=music
        fields=['name','desc','year','img']

musicproject/mcproject/musicapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import music
from . forms import MusicForm
# Create your views here.
def index(request):
    mc=music.objects.all()
    context={
        'music_list':mc
    }

    return render(request,'index.html',context)
def detail(request,music_id):
    music1=music.objects.get(id=music_id)
    return render(request,"detail.html",{'music':music1})

def add_music(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        music1=music(name=name,desc=desc,year=year,img=img)
        music1.save()

    return render(request,'add.html')

def update(request,id):
    music2=music.objects.get(id=id)
    form=MusicForm(request.POST or None,request.FILES,instance=music2)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'music':music2})

def delete(request,id):
    if request.method=='POST':
        music3=music.objects.get(id=id)
        music3.delete()
        return redirect('/')
    return render(request,'delete.html')

musicproject/mcproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="enter your music name"><br>
     <input type="text" name="desc" placeholder="enter your music description"><br>
     <input type="text" name="year" placeholder="enter your music year"><br>
     <input type="file" name="img"><br>
     <input type="submit">

</form>
{% endblock %}

musicproject/mcproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>music</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    online music collection
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

musicproject/mcproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  Are you want delete this music?
  <input type="submit">

</form>

musicproject/mcproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{music.img.url}}" width="300" height="300">
        </div>
<div class="col-md-6">
    <h2>{{music.name}}</h2>
    <h4>{{music.desc}}</h4>
    <h6>{{music.year}}</h6>
    <a class="btn btn-warning" href="{% url 'musicapp:update' music.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'musicapp:delete' music.id %}">delete</a>
</div>

    </div>
</div>
{% endblock %}

musicproject/mcproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>

musicproject/mcproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in music_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'musicapp:detail' i.id %}" class="btn btn-primary">view details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}